### ISSUE TITLE
Missing dependency: spelling

### ISSUE THREAD

**Issue by rlrichards** [mvevans89/woRdle#1]
Appears to rely on the package `spelling` but does not require it as a dependency. Error references the function loadNamespace(x).

**Comment by mvevans89** [comment]
This better not be what the `man` page was for...

**Comment by mvevans89** [comment]
This is fixed for now, but the package isn't currently automatically updated via `roxygen2`. The fix included listing `spelling` as an `@imports` so it should transfer okay

**Comment by rlrichards** [comment]
That should do it. Also roxygen should write the man pages for you!
