### ISSUE TITLE
add a check for word length

### ISSUE THREAD

**Issue by mvevans89** [mvevans89/woRdle#2]
While there is currently something to make sure the word is actually a word, there is nothing to check it is the right length (5 letters). Submitting the incorrect length will likely break things.

**Comment by rlrichards** [comment]
Yes. Submitting a 6 letter word adds the 6th letter as the first letter of the next word in the graphic. Not sure what happens under the hood but it does appear to reset the checker for the next guess. It just doesn't reset the row of the graphic.

**Comment by rlrichards** [comment]
At the end of the game it does spit out warnings for the length mismatch.
