### ISSUE TITLE
TELL US THE WORD MICHELLE

### ISSUE THREAD

**Issue by rlrichards** [mvevans89/woRdle#4]
I like the print out of the guesses in ascii but it doesn't tell us what the correct answer is if you don't get it in 6 guesses. Perhaps append this at the top or bottom of the print out.

**Comment by mvevans89** [comment]
not to brag but I have never not gotten the wordle so I honestly did not know this was a feature

**Comment by rlrichards** [comment]
I'm actually not sure whether it is or not either....I have gotten it wrong but too long ago now. Does seem like it would though. Though now that I've realized that the word stays the same for the whole day in this version too maybe it's less necessary.

**Comment by mvevans89** [comment]
is that not what happens in normal wordle? I thought it was like a daily thing? You can also choose another day by just providing any other date post feb 1 2022

**Comment by rlrichards** [comment]
Oh yeah it totally is. I just for some reason assumed this version would play with a random word each time. Don't know why.

**Comment by mvevans89** [comment]
it should tell the people who didn't make it the word at the end now. debating adding this as an argument so that those who want to retry don't see the word, but leaving it for now
